author: 'Steve-L' # 作者名称
author_avatar:  # 作者头像
  local_path: "/static/img/head pic.gif"
  # rounded: true
  # rotated: true

author_text: '个人的一些整理' # 作者信息
social: # 社交链接
  - title: 'Github'
    icon: 'github'
    link: 'https://github.com/'
    stacked: false
  - title: 'ChatGPT'
    icon: 'commenting-o'
    link: 'https://chat.openai.com'
    stacked: false
  - title: '谷歌翻译'
    icon: 'exchange'
    link: 'https://translate.google.com/'
    stacked: false

# background: 'https://api.paugram.com/wallpaper?source=gh' # 主题背景
menu: # 页眉菜单项目
  #'关于我': /about
  #'朋友们': /friends
config:
  copyright: true # 复制的时候弹出保留原站链接说明
  night: true # 自动切换夜间模式
  